name: Build binaries
on:
  push:
    branches: [ "master" ]
    tags: [ v* ]

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux_headless_cli
            bin: target/release/headless_cli

          - release_for: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows_headless_cli
            bin: target/release/headless_cli.exe

          - release_for: Mac
            os: macOS-latest
            target: x86_64-apple-darwin
            name: mac_headless_cli
            bin: target/release/headless_cli

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --all-features
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ matrix.platform.bin }}
  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Release
        env:
          TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'v0.0.7' }}
        run: |
          echo "Creating release"
          ls -lah mac_headless_cli
          gh release create $TAG
          gh release upload $TAG "linux_headless_cli/headless_cli#linux" "windows_headless_cli/headless_cli.exe#windows" "mac_headless_cli/headless_cli#macos"
